In [1]:
import pandas as pd

gdp = pd.read_csv("data/gdp-pcap.csv")
gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,26129.839060,27458.225330,27441.529660,28440.051960,30082.127640,31096.205070,22855.932320,27200.061080,30559.533530,33984.790620
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.132432,186.947182,197.408105,225.447007,209.005786,226.883067,...,1656.107642,1479.564123,1329.777824,1520.171298,1538.924188,1493.780445,1344.080962,1522.590088,1628.024526,1659.515290
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,625.054942,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,415.707417
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.938353,127.452629,133.825452,139.006714,148.547736,155.563837,...,2204.995700,1845.767804,1616.843198,1560.162999,1703.896392,1783.654365,1664.249176,1747.840549,1777.235012,1568.724310
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5005.999741,3213.902611,1807.952941,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2308.159767

In [2]:
import pandas as pd

# Load the dataset
gdp = pd.read_csv("data/gdp-pcap.csv")

# Identify year columns (all numeric column names)
year_cols = [col for col in gdp.columns if col.isdigit()]

# All other columns are ID columns
id_cols = [col for col in gdp.columns if col not in year_cols]

# Melt the dataframe to long format
gdp_long = gdp.melt(id_vars=id_cols, var_name="Year", value_name="GDP_per_capita")

# Convert Year to integer
gdp_long["Year"] = gdp_long["Year"].astype(int)

# Optional: View result
print(gdp_long.head())

                  Country Name Country Code                Indicator Name  \
0                        Aruba          ABW  GDP per capita (current US$)
1  Africa Eastern and Southern          AFE  GDP per capita (current US$)
2                  Afghanistan          AFG  GDP per capita (current US$)
3   Africa Western and Central          AFW  GDP per capita (current US$)
4                       Angola          AGO  GDP per capita (current US$)

   Indicator Code  Year  GDP_per_capita
0  NY.GDP.PCAP.CD  1960             NaN
1  NY.GDP.PCAP.CD  1960      186.132432
2  NY.GDP.PCAP.CD  1960             NaN
3  NY.GDP.PCAP.CD  1960      121.938353
4  NY.GDP.PCAP.CD  1960             NaN

In [3]:
import pandas as pd

# Load the inflation dataset
inflation = pd.read_csv("data/inflation.csv")

# Identify year columns (all numeric column names)
year_cols = [col for col in inflation.columns if col.isdigit()]

# All other columns are ID columns
id_cols = [col for col in inflation.columns if col not in year_cols]

# Melt the dataframe
inflation_long = inflation.melt(id_vars=id_cols, var_name="Year", value_name="Inflation")

# Convert 'Year' to integer
inflation_long["Year"] = inflation_long["Year"].astype(int)

# Preview
print(inflation_long.head())

                  Country Name Country Code  \
0                        Aruba          ABW
1  Africa Eastern and Southern          AFE
2                  Afghanistan          AFG
3   Africa Western and Central          AFW
4                       Angola          AGO

                          Indicator Name  Indicator Code  Year  Inflation
0  Inflation, consumer prices (annual %)  FP.CPI.TOTL.ZG  1960        NaN
1  Inflation, consumer prices (annual %)  FP.CPI.TOTL.ZG  1960        NaN
2  Inflation, consumer prices (annual %)  FP.CPI.TOTL.ZG  1960        NaN
3  Inflation, consumer prices (annual %)  FP.CPI.TOTL.ZG  1960        NaN
4  Inflation, consumer prices (annual %)  FP.CPI.TOTL.ZG  1960        NaN

In [4]:
import pandas as pd

# Load the deflation dataset
deflation = pd.read_csv("data/deflation.csv")

# Identify year columns (those that are digits)
year_cols = [col for col in deflation.columns if col.isdigit()]

# Identify id columns (the rest)
id_cols = [col for col in deflation.columns if col not in year_cols]

# Melt the dataframe into long format
deflation_long = deflation.melt(id_vars=id_cols, var_name="Year", value_name="Deflation")

# Convert 'Year' to integer
deflation_long["Year"] = deflation_long["Year"].astype(int)

# Preview
print(deflation_long.head())

                  Country Name Country Code  \
0                        Aruba          ABW
1  Africa Eastern and Southern          AFE
2                  Afghanistan          AFG
3   Africa Western and Central          AFW
4                       Angola          AGO

                               Indicator Name  Indicator Code  Year  Deflation
0  GDP deflator (base year varies by country)  NY.GDP.DEFL.ZS  1960        NaN
1  GDP deflator (base year varies by country)  NY.GDP.DEFL.ZS  1960        NaN
2  GDP deflator (base year varies by country)  NY.GDP.DEFL.ZS  1960        NaN
3  GDP deflator (base year varies by country)  NY.GDP.DEFL.ZS  1960        NaN
4  GDP deflator (base year varies by country)  NY.GDP.DEFL.ZS  1960        NaN

In [5]:
import pandas as pd

# Load the FAO dataset
fao = pd.read_csv("data/fao-data.csv")

# Select only useful columns
fao_clean = fao[[
    "Area", "Year", "Item", "Element", "Unit", "Value"
]].copy()

# Rename for consistency with other datasets
fao_clean = fao_clean.rename(columns={
    "Area": "Country Name"
})

# Optional: Clean up countries (if needed) or drop missing
fao_clean = fao_clean.dropna(subset=["Country Name", "Year", "Value"])

# Preview
print(fao_clean.head())

  Country Name  Year                                        Item Element Unit  \
0  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
1  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
2  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
3  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
4  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN

       Value
0  24.356332
1  23.636242
2  23.485345
3  24.767194
4  25.956912

In [6]:
import pandas as pd

# Load the FAO dataset
fao_data = pd.read_csv("data/fao-data.csv")

# Select only useful columns
fao_data_clean = fao_data[[
    "Area", "Year", "Item", "Element", "Unit", "Value"
]].copy()

# Rename for consistency with other datasets
fao_data_clean = fao_data_clean.rename(columns={
    "Area": "Country Name"
})

# Optional: Clean up countries (if needed) or drop missing
fao_data_clean = fao_data_clean.dropna(subset=["Country Name", "Year", "Value"])

# Preview
print(fao_data_clean.head())

  Country Name  Year                                        Item Element Unit  \
0  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
1  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
2  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
3  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN
4  Afghanistan  2000  Consumer Prices, Food Indices (2015 = 100)   Value  NaN

       Value
0  24.356332
1  23.636242
2  23.485345
3  24.767194
4  25.956912

In [7]:
import pandas as pd

# Load the Tariff dataset
tariff_data = pd.read_csv("data/tariff_data.csv")

# Rename 'Entity' to 'Country Name' for consistency
tariff_data = tariff_data.rename(columns={
    "Entity": "Country Name",
    "Tariff rate, applied, weighted mean, all products (%)": "Tariff Rate (%)"
})

# Optional: Drop rows with missing data in 'Country Name' or 'Year' (if needed)
tariff_data = tariff_data.dropna(subset=["Country Name", "Year"])

# Preview
print(tariff_data.head())

  Country Name Code  Year  Tariff Rate (%)
0  Afghanistan  AFG  2004             4.01
1  Afghanistan  AFG  2006             7.79
2  Afghanistan  AFG  2007             7.80
3  Afghanistan  AFG  2008             5.00
4  Afghanistan  AFG  2012             5.47

In [8]:
import pandas as pd

# Load the dataset
sixth_data = pd.read_csv("data/sixth_data.csv")

# Melt the data to long format (years as rows, instead of columns)
sixth_data_clean = pd.melt(sixth_data,
                           id_vars=["Area", "Item", "Element", "Unit"],
                           value_vars=[f"Y{year}" for year in range(1991, 2025)],
                           var_name="Year", value_name="Value")

# Remove "Y" from year column
sixth_data_clean["Year"] = sixth_data_clean["Year"].str[1:].astype(int)

# Rename for consistency with other datasets
sixth_data_clean = sixth_data_clean.rename(columns={
    "Area": "Country Name",
    "Item": "Item Name",
    "Element": "Element Name"
})

# Optional: Drop rows with missing 'Country Name', 'Year', or 'Value'
sixth_data_clean = sixth_data_clean.dropna(subset=["Country Name", "Year", "Value"])

# Preview the cleaned data
print(sixth_data_clean.head())

   Country Name                                          Item Name  \
2   Afghanistan                                  Almonds, in shell
3   Afghanistan  Anise, badian, coriander, cumin, caraway, fenn...
6   Afghanistan                                             Apples
9   Afghanistan                                           Apricots
12  Afghanistan                                             Barley

                              Element Name Unit  Year   Value
2   Producer Price Index (2014-2016 = 100)  NaN  1991   21.57
3   Producer Price Index (2014-2016 = 100)  NaN  1991   10.62
6   Producer Price Index (2014-2016 = 100)  NaN  1991   25.13
9   Producer Price Index (2014-2016 = 100)  NaN  1991  130.06
12  Producer Price Index (2014-2016 = 100)  NaN  1991  183.58

In [9]:
# Merge all six datasets based on 'Country Name' and 'Year'
final_df = gdp_long.merge(inflation_long, on=["Country Name", "Year"], how="outer")
final_df = final_df.merge(deflation_long, on=["Country Name", "Year"], how="outer")
final_df = final_df.merge(fao_data_clean, on=["Country Name", "Year"], how="outer")
final_df = final_df.merge(tariff_data, on=["Country Name", "Year"], how="outer")
final_df = final_df.merge(sixth_data_clean, on=["Country Name", "Year"], how="outer")

# Preview the final merged dataset
#print(final_df.head())

In [10]:
print(final_df.head())

  Country Name Country Code_x              Indicator Name_x Indicator Code_x  \
0  Afghanistan            AFG  GDP per capita (current US$)   NY.GDP.PCAP.CD
1  Afghanistan            AFG  GDP per capita (current US$)   NY.GDP.PCAP.CD
2  Afghanistan            AFG  GDP per capita (current US$)   NY.GDP.PCAP.CD
3  Afghanistan            AFG  GDP per capita (current US$)   NY.GDP.PCAP.CD
4  Afghanistan            AFG  GDP per capita (current US$)   NY.GDP.PCAP.CD

   Year  GDP_per_capita Country Code_y                       Indicator Name_y  \
0  1960             NaN            AFG  Inflation, consumer prices (annual %)
1  1961             NaN            AFG  Inflation, consumer prices (annual %)
2  1962             NaN            AFG  Inflation, consumer prices (annual %)
3  1963             NaN            AFG  Inflation, consumer prices (annual %)
4  1964             NaN            AFG  Inflation, consumer prices (annual %)

  Indicator Code_y  Inflation  ... Item Element Unit_x  Value_x Code  \
0   FP.CPI.TOTL.ZG        NaN  ...  NaN     NaN    NaN      NaN  NaN
1   FP.CPI.TOTL.ZG        NaN  ...  NaN     NaN    NaN      NaN  NaN
2   FP.CPI.TOTL.ZG        NaN  ...  NaN     NaN    NaN      NaN  NaN
3   FP.CPI.TOTL.ZG        NaN  ...  NaN     NaN    NaN      NaN  NaN
4   FP.CPI.TOTL.ZG        NaN  ...  NaN     NaN    NaN      NaN  NaN

  Tariff Rate (%) Item Name  Element Name Unit_y  Value_y
0             NaN       NaN           NaN    NaN      NaN
1             NaN       NaN           NaN    NaN      NaN
2             NaN       NaN           NaN    NaN      NaN
3             NaN       NaN           NaN    NaN      NaN
4             NaN       NaN           NaN    NaN      NaN

[5 rows x 24 columns]

In [11]:
final_df.to_csv('Final.csv', sep='\t', index=False,header=True)